add multiple account support for env config
AsterNighT/sisyphus pull request #2
Opened 2022-05-10 07:00 UTC by FUTURETECH6

2022-05-10 15:49 UTC, AsterNighT requested changes
Just a few tweaks

2022-05-10 15:49 UTC, AsterNighT commented on src/main.ts
> +    const usernameArray = (process.env.ZJU_USERNAME || reportFatal('ZJU_USERNAME not set')).split(",")
```suggestion
    const usernameArray = (process.env.ZJU_USERNAME || reportFatal('ZJU_USERNAME not set')).split(",").map(s => s.trim());
```

2022-05-10 15:49 UTC, AsterNighT commented on src/main.ts
> +    const passwordArray = (process.env.ZJU_PASSWORD || reportFatal('ZJU_PASSWORD not set')).split(",")
```suggestion
    const passwordArray = (process.env.ZJU_PASSWORD || reportFatal('ZJU_PASSWORD not set')).split(",").map(s => s.trim());
```

2022-05-10 15:49 UTC, AsterNighT commented on src/main.ts
> +        console.error("username and password length mismatch, please use comma ',' without whitespace")
```suggestion
        console.error("username and password length mismatch");
```

2022-05-10 15:49 UTC, AsterNighT commented on src/main.ts
> +    let accountArray = new Array();
```suggestion
    const accountArray = usernameArray.map((username,i) => ({username, password: passwordArray[i]});
```

2022-05-10 16:16 UTC, AsterNighT commented on src/main.ts
> +    if (usernameArray.length != passwordArray.length) {
```suggestion
    if (usernameArray.length !== passwordArray.length) {
```

2022-05-11 04:29 UTC, FUTURETECH6 commented
> Just a few tweaks

not familiar with js 😅

2022-05-11 05:53 UTC, AsterNighT approved these changes
LGTM

2022-05-11 05:54 UTC, merged